apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/duke-admin-authentication-service
  newTag: 0e4f630e

configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: duke-admin-authentication-service-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: duke-admin-authentication-service-secret-env

patches:
- path: patches/set_resources.yaml
