apiVersion: apps/v1
kind: Deployment
metadata:
  name: duke-admin-authentication-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: duke-admin-authentication-service
          resources:
            limits:
              cpu: 300m
              memory: 64Mi
            requests:
              cpu: 200m
              memory: 32Mi
